services:
  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 5000 --workers 4
    ports:
      - "5000:5000"
    networks:
      - web

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/app:/app
      - /app/node_modules
    networks:
      - web

networks:
  web:
